site_name: OSG Virtual School Pilot 2020
site_url: https://opensciencegrid.org/virtual-school-pilot-2020/
repo_name: null
repo_url: null
theme:
  name: windmill
  custom_dir: theme-customizations

extra:
  article_nav_top: false

extra_css:
  - css/extra.css
  - css/codehilite.css

# Suppress weird JavaScript problems with development server
extra_javascript: []

pages:
  - Virtual School Pilot 2020:    index.md
  - Schedule:                     schedule.md
  - Materials:
    - Overview:                   materials/index.md
    - HTC Exercises:
      - Exercise 1.1:             materials/htc/part1-ex1-login.md
      - Exercise 1.2:             materials/htc/part1-ex2-commands.md
      - Exercise 1.3:             materials/htc/part1-ex3-jobs.md
      - Exercise 1.4:             materials/htc/part1-ex4-logs.md
      - Exercise 1.5:             materials/htc/part1-ex5-request.md
      - Exercise 1.6:             materials/htc/part1-ex6-remove.md
      - Bonus Exercise 1.7:       materials/htc/part1-ex7-compile.md
      - Exercise 2.1:             materials/htc/part2-ex1-files.md
      - Exercise 2.2:             materials/htc/part2-ex2-queue-n.md
      - Exercise 2.3:             materials/htc/part2-ex3-queue-from.md
      - Bonus Exercise 2.4:       materials/htc/part2-ex4-queue-matching.md
      - Bonus Exercise 3.1:       materials/htc/part3-ex1-queue.md
      - Bonus Exercise 3.2:       materials/htc/part3-ex2-status.md
      - Bonus Exercise 3.3:       materials/htc/part3-ex3-job-retry.md
    - Grid Exercises:
      - Exercise 1:               materials/osg/ex1-submit-refresher.md
      - Exercise 2:               materials/osg/ex2-login-scp.md
      - Exercise 3:               materials/osg/ex3-submit-osg.md
      - Exercise 4:               materials/osg/ex4-hardware-diffs.md
      - Exercise 5:               materials/osg/ex5-software-diffs.md
    - Software Exercises:
      - Exercise 1.1:             materials/sw/part1-ex1-download.md
      - Exercise 1.2:             materials/sw/part1-ex2-wrapper.md
      - Exercise 2.1:             materials/sw/part2-ex1-compiling.md
      - Exercise 2.2:             materials/sw/part2-ex2-prepackaged.md
      - Exercise 2.3:             materials/sw/part2-ex3-python.md
      - Exercise 2.4:             materials/sw/part2-ex4-matlab.md
      - Exercise 3.1:             materials/sw/part3-ex1-singularity.md
      - Exercise 4.1:             materials/sw/part4-ex1-arguments.md
      - Exercise 4.2:             materials/sw/part4-ex2-python-extras.md
      - Exercise 4.3:             materials/sw/part4-ex3-docker.md
    - Data Exercises:
      - Placeholder:              materials/data/temp.md
  - Staff:                        staff.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - osg_markdown.colors
